import AppUtil from "@/AppUtil";
import { IClaim, IPaginationQuery, IPostResponse, Pagination } from "@/types";
import { configureStore } from "@reduxjs/toolkit";
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

let cliams = {
  totalClaims: 12,
  totalAdvances: 8,
  claimdata: [
    {
      status: 1,
      statusName: null,
      currencyCode: "MYR",
      currencyName: "Malaysian ringgit",
      totalAmount: 663.12,
      totalCount: 1,
      totalClaimableAmount: 663.12,
      expensesCount: 3,
      mileagesCount: 1,
      advancesCount: 1,
      perDiemsCount: 3,
      expensesAmount: 511.12,
      mileagesAmount: 260,
      advancesAmount: 200,
      perDiemsAmount: 92,
    },
    {
      status: 4,
      statusName: null,
      currencyCode: "MYR",
      currencyName: "Malaysian ringgit",
      totalAmount: 7835.81,
      totalCount: 4,
      totalClaimableAmount: 7835.81,
      expensesCount: 6,
      mileagesCount: 1,
      advancesCount: 1,
      perDiemsCount: 1,
      expensesAmount: 735.81,
      mileagesAmount: 8000,
      advancesAmount: 900,
      perDiemsAmount: 0,
    },
    {
      status: 2,
      statusName: null,
      currencyCode: "MYR",
      currencyName: "Malaysian ringgit",
      totalAmount: 513.81,
      totalCount: 1,
      totalClaimableAmount: 513.81,
      expensesCount: 3,
      mileagesCount: 0,
      advancesCount: 0,
      perDiemsCount: 0,
      expensesAmount: 513.81,
      mileagesAmount: 0,
      advancesAmount: 0,
      perDiemsAmount: 0,
    },
    {
      status: 4,
      statusName: null,
      currencyCode: "SGD",
      currencyName: "Singapore dollar",
      totalAmount: 1469.67,
      totalCount: 1,
      totalClaimableAmount: 485.81,
      expensesCount: 3,
      mileagesCount: 0,
      advancesCount: 0,
      perDiemsCount: 0,
      expensesAmount: 1469.67,
      mileagesAmount: 0,
      advancesAmount: 0,
      perDiemsAmount: 0,
    },
    {
      status: 3,
      statusName: null,
      currencyCode: "MYR",
      currencyName: "Malaysian ringgit",
      totalAmount: 28749.13,
      totalCount: 5,
      totalClaimableAmount: 28300,
      expensesCount: 5,
      mileagesCount: 3,
      advancesCount: 2,
      perDiemsCount: 2,
      expensesAmount: 12999.13,
      mileagesAmount: 16120,
      advancesAmount: 400,
      perDiemsAmount: 30,
    },
  ],
  advancedata: [
    {
      status: 1,
      statusName: null,
      currencyCode: "MYR",
      currencyName: "Malaysian ringgit",
      totalAmount: 702.76,
      totalCount: 1,
    },
    {
      status: 2,
      statusName: null,
      currencyCode: "MYR",
      currencyName: "Malaysian ringgit",
      totalAmount: 200,
      totalCount: 2,
    },
    {
      status: 4,
      statusName: null,
      currencyCode: "MYR",
      currencyName: "Malaysian ringgit",
      totalAmount: 1300,
      totalCount: 3,
    },
    {
      status: 5,
      statusName: null,
      currencyCode: "AUD",
      currencyName: "Australian dollar",
      totalAmount: 200,
      totalCount: 1,
    },
    {
      status: 5,
      statusName: null,
      currencyCode: "MYR",
      currencyName: "Malaysian ringgit",
      totalAmount: 100,
      totalCount: 1,
    },
  ],
  recentClaims: [
    {
      id: 17,
      startDate: "2024-08-19 08:00 AM",
      endDate: "2024-08-20 07:59 AM",
      currencyCode: "MYR",
      name: "reder",
      purpose: "reder",
      costCentreId: 46,
      costCentreName: null,
      overBudget: null,
      overBudgetReason: null,
      unaccountedAdvances: null,
      status: 4,
      submittedOn: "2024-08-19T03:39:38.578979Z",
      displaySubmittedOn: "2024-08-19 11:39 AM",
      expenses: [
        {
          expenseId: 25,
          expenseTypeID: 83,
          expenseTypeName: null,
          expenseSubTypeID: 0,
          expenseSubTypeName: null,
          storeID: 767,
          storeName: null,
          brandID: 267,
          brandName: null,
          prodCatID: 1543,
          prodCatName: null,
          natureofExpense: null,
          natureofExpenseReason: null,
          currencyCode: "MYR",
          currencyName: null,
          vendorCategory: null,
          notes: "rrrer",
          amount: 100,
          date: "2024-08-19",
          displayDate: "2024-08-19",
          receiptPath: "",
          paymentMethod: 1593,
          cardId: null,
          supplier: null,
          invoiceNumber: null,
          tax: 0,
          listOfParticipants: null,
          foreignCurrencyCode: null,
          foreignAmount: null,
          exchangeRate: null,
        },
      ],
      perDiems: [],
      mileages: [],
      advances: [],
      approvalSteps: [],
      totalReceipts: 0,
      totalExpenseAmount: 100,
      totalPerDiemAmount: 0,
      totalMileageAmount: 0,
      totalAdvanceAmount: 0,
      totalCardAmount: 0,
      totalSpentAmount: 100,
      totalAmount: 100,
      totalClaimableAmount: 100,
      createdByUser: {
        id: "57b41de6-363a-48d2-bc4e-20e84ef67791",
        userName: "superadmin",
        email: "k.a.n.shafeeq@gmail.com",
        firstName: "Super",
        lastName: "Admin",
        employeeID: "V009782",
        departmentID: 11,
        departmentName: null,
        gradeID: 1588,
        gradeName: null,
        companyID: 2,
        companyName: null,
        storeID: 767,
        storeName: null,
        brandID: 267,
        brandName: null,
        prodCatID: 1543,
        prodCatName: null,
        costCentreId: 46,
        costCentreName: null,
        designation: "IT Admin",
        countryCode: "MY",
        currencyCode: "MYR",
        picturePath: null,
        pictureBase64: null,
        role: null,
        isActive: true,
      },
      displayCreatedOn: "2024-08-19 11:38 AM",
      displayLastModifiedOn: "2024-08-19 11:41 AM",
      createdBy: "57b41de6-363a-48d2-bc4e-20e84ef67791",
      createdOn: "2024-08-19T03:38:52.54268Z",
      lastModifiedBy: "57b41de6-363a-48d2-bc4e-20e84ef67791",
      lastModifiedOn: "2024-08-19T03:41:07.386189Z",
    },
    {
      id: 16,
      startDate: "2024-08-18 08:00 AM",
      endDate: "2024-08-19 07:59 AM",
      currencyCode: "MYR",
      name: "Test",
      purpose: "rest",
      costCentreId: 46,
      costCentreName: null,
      overBudget: null,
      overBudgetReason: null,
      unaccountedAdvances: null,
      status: 4,
      submittedOn: "2024-08-18T14:59:51.238337Z",
      displaySubmittedOn: "2024-08-18 10:59 PM",
      expenses: [
        {
          expenseId: 24,
          expenseTypeID: 82,
          expenseTypeName: null,
          expenseSubTypeID: 0,
          expenseSubTypeName: null,
          storeID: 767,
          storeName: null,
          brandID: 267,
          brandName: null,
          prodCatID: 1543,
          prodCatName: null,
          natureofExpense: null,
          natureofExpenseReason: null,
          currencyCode: "MYR",
          currencyName: null,
          vendorCategory: null,
          notes: "reed",
          amount: 100,
          date: "2024-08-18",
          displayDate: "2024-08-18",
          receiptPath: "",
          paymentMethod: 1593,
          cardId: null,
          supplier: null,
          invoiceNumber: null,
          tax: 0,
          listOfParticipants: null,
          foreignCurrencyCode: null,
          foreignAmount: null,
          exchangeRate: null,
        },
      ],
      perDiems: [],
      mileages: [],
      advances: [],
      approvalSteps: [],
      totalReceipts: 0,
      totalExpenseAmount: 100,
      totalPerDiemAmount: 0,
      totalMileageAmount: 0,
      totalAdvanceAmount: 0,
      totalCardAmount: 0,
      totalSpentAmount: 100,
      totalAmount: 100,
      totalClaimableAmount: 100,
      createdByUser: {
        id: "57b41de6-363a-48d2-bc4e-20e84ef67791",
        userName: "superadmin",
        email: "k.a.n.shafeeq@gmail.com",
        firstName: "Super",
        lastName: "Admin",
        employeeID: "V009782",
        departmentID: 11,
        departmentName: null,
        gradeID: 1588,
        gradeName: null,
        companyID: 2,
        companyName: null,
        storeID: 767,
        storeName: null,
        brandID: 267,
        brandName: null,
        prodCatID: 1543,
        prodCatName: null,
        costCentreId: 46,
        costCentreName: null,
        designation: "IT Admin",
        countryCode: "MY",
        currencyCode: "MYR",
        picturePath: null,
        pictureBase64: null,
        role: null,
        isActive: true,
      },
      displayCreatedOn: "2024-08-18 10:59 PM",
      displayLastModifiedOn: "2024-08-18 11:01 PM",
      createdBy: "57b41de6-363a-48d2-bc4e-20e84ef67791",
      createdOn: "2024-08-18T14:59:12.775275Z",
      lastModifiedBy: "57b41de6-363a-48d2-bc4e-20e84ef67791",
      lastModifiedOn: "2024-08-18T15:01:03.849927Z",
    },
    {
      id: 15,
      startDate: "2024-08-18 08:00 AM",
      endDate: "2024-08-19 07:59 AM",
      currencyCode: "MYR",
      name: "rerer",
      purpose: "rerer",
      costCentreId: 46,
      costCentreName: null,
      overBudget: null,
      overBudgetReason: null,
      unaccountedAdvances: null,
      status: 3,
      submittedOn: "2024-08-18T14:45:44.74028Z",
      displaySubmittedOn: "2024-08-18 10:45 PM",
      expenses: [
        {
          expenseId: 23,
          expenseTypeID: 83,
          expenseTypeName: null,
          expenseSubTypeID: 0,
          expenseSubTypeName: null,
          storeID: 767,
          storeName: null,
          brandID: 267,
          brandName: null,
          prodCatID: 1543,
          prodCatName: null,
          natureofExpense: null,
          natureofExpenseReason: null,
          currencyCode: "MYR",
          currencyName: null,
          vendorCategory: null,
          notes: "red",
          amount: 100,
          date: "2024-08-18",
          displayDate: "2024-08-18",
          receiptPath: "",
          paymentMethod: 1593,
          cardId: null,
          supplier: null,
          invoiceNumber: null,
          tax: 0,
          listOfParticipants: null,
          foreignCurrencyCode: null,
          foreignAmount: null,
          exchangeRate: null,
        },
      ],
      perDiems: [],
      mileages: [],
      advances: [],
      approvalSteps: [],
      totalReceipts: 0,
      totalExpenseAmount: 100,
      totalPerDiemAmount: 0,
      totalMileageAmount: 0,
      totalAdvanceAmount: 0,
      totalCardAmount: 0,
      totalSpentAmount: 100,
      totalAmount: 100,
      totalClaimableAmount: 100,
      createdByUser: {
        id: "57b41de6-363a-48d2-bc4e-20e84ef67791",
        userName: "superadmin",
        email: "k.a.n.shafeeq@gmail.com",
        firstName: "Super",
        lastName: "Admin",
        employeeID: "V009782",
        departmentID: 11,
        departmentName: null,
        gradeID: 1588,
        gradeName: null,
        companyID: 2,
        companyName: null,
        storeID: 767,
        storeName: null,
        brandID: 267,
        brandName: null,
        prodCatID: 1543,
        prodCatName: null,
        costCentreId: 46,
        costCentreName: null,
        designation: "IT Admin",
        countryCode: "MY",
        currencyCode: "MYR",
        picturePath: null,
        pictureBase64: null,
        role: null,
        isActive: true,
      },
      displayCreatedOn: "2024-08-18 10:45 PM",
      displayLastModifiedOn: "2024-08-18 10:46 PM",
      createdBy: "57b41de6-363a-48d2-bc4e-20e84ef67791",
      createdOn: "2024-08-18T14:45:18.919895Z",
      lastModifiedBy: "57b41de6-363a-48d2-bc4e-20e84ef67791",
      lastModifiedOn: "2024-08-18T14:46:32.808676Z",
    },
  ],
  recentAdvances: [
    {
      advanceId: 12,
      advanceType: 1595,
      paymentMethod: 1590,
      storeID: 767,
      storeName: null,
      brandID: 267,
      brandName: null,
      prodCatID: 1543,
      prodCatName: null,
      costCentreId: 46,
      costCentreName: null,
      currencyCode: "MYR",
      currencyName: null,
      purpose: "rede",
      notes: "rerer",
      amount: 100,
      date: "2024-08-19",
      displayDate: "2024-08-19",
      receiptPath: "",
      status: 2,
      cardId: null,
      corporateCard: null,
      approvalSteps: [],
      tripId: null,
      createdBy: "57b41de6-363a-48d2-bc4e-20e84ef67791",
      createdByUser: {
        id: "57b41de6-363a-48d2-bc4e-20e84ef67791",
        userName: "superadmin",
        email: "k.a.n.shafeeq@gmail.com",
        firstName: "Super",
        lastName: "Admin",
        employeeID: "V009782",
        departmentID: 11,
        departmentName: null,
        gradeID: 1588,
        gradeName: null,
        companyID: 2,
        companyName: null,
        storeID: 767,
        storeName: null,
        brandID: 267,
        brandName: null,
        prodCatID: 1543,
        prodCatName: null,
        costCentreId: 46,
        costCentreName: null,
        designation: "IT Admin",
        countryCode: "MY",
        currencyCode: "MYR",
        picturePath: null,
        pictureBase64: null,
        role: null,
        isActive: true,
      },
      createdOn: "2024-08-19T04:53:05.92595Z",
      displayCreatedOn: "2024-08-19 12:53 PM",
      foreignCurrencyCode: null,
      foreignAmount: null,
      exchangeRate: null,
    },
    {
      advanceId: 11,
      advanceType: 1596,
      paymentMethod: 1590,
      storeID: 767,
      storeName: null,
      brandID: 267,
      brandName: null,
      prodCatID: 1543,
      prodCatName: null,
      costCentreId: 46,
      costCentreName: null,
      currencyCode: "MYR",
      currencyName: null,
      purpose: "test",
      notes: "res",
      amount: 100,
      date: "2024-08-19",
      displayDate: "2024-08-19",
      receiptPath: "",
      status: 5,
      cardId: null,
      corporateCard: null,
      approvalSteps: [],
      tripId: null,
      createdBy: "57b41de6-363a-48d2-bc4e-20e84ef67791",
      createdByUser: {
        id: "57b41de6-363a-48d2-bc4e-20e84ef67791",
        userName: "superadmin",
        email: "k.a.n.shafeeq@gmail.com",
        firstName: "Super",
        lastName: "Admin",
        employeeID: "V009782",
        departmentID: 11,
        departmentName: null,
        gradeID: 1588,
        gradeName: null,
        companyID: 2,
        companyName: null,
        storeID: 767,
        storeName: null,
        brandID: 267,
        brandName: null,
        prodCatID: 1543,
        prodCatName: null,
        costCentreId: 46,
        costCentreName: null,
        designation: "IT Admin",
        countryCode: "MY",
        currencyCode: "MYR",
        picturePath: null,
        pictureBase64: null,
        role: null,
        isActive: true,
      },
      createdOn: "2024-08-19T04:46:28.934797Z",
      displayCreatedOn: "2024-08-19 12:46 PM",
      foreignCurrencyCode: null,
      foreignAmount: null,
      exchangeRate: null,
    },
    {
      advanceId: 10,
      advanceType: 1596,
      paymentMethod: 1590,
      storeID: 767,
      storeName: null,
      brandID: 267,
      brandName: null,
      prodCatID: 1543,
      prodCatName: null,
      costCentreId: 46,
      costCentreName: null,
      currencyCode: "MYR",
      currencyName: null,
      purpose: "terer",
      notes: "rest",
      amount: 100,
      date: "2024-08-19",
      displayDate: "2024-08-19",
      receiptPath: "",
      status: 2,
      cardId: null,
      corporateCard: null,
      approvalSteps: [],
      tripId: null,
      createdBy: "57b41de6-363a-48d2-bc4e-20e84ef67791",
      createdByUser: {
        id: "57b41de6-363a-48d2-bc4e-20e84ef67791",
        userName: "superadmin",
        email: "k.a.n.shafeeq@gmail.com",
        firstName: "Super",
        lastName: "Admin",
        employeeID: "V009782",
        departmentID: 11,
        departmentName: null,
        gradeID: 1588,
        gradeName: null,
        companyID: 2,
        companyName: null,
        storeID: 767,
        storeName: null,
        brandID: 267,
        brandName: null,
        prodCatID: 1543,
        prodCatName: null,
        costCentreId: 46,
        costCentreName: null,
        designation: "IT Admin",
        countryCode: "MY",
        currencyCode: "MYR",
        picturePath: null,
        pictureBase64: null,
        role: null,
        isActive: true,
      },
      createdOn: "2024-08-19T04:41:40.699578Z",
      displayCreatedOn: "2024-08-19 12:41 PM",
      foreignCurrencyCode: null,
      foreignAmount: null,
      exchangeRate: null,
    },
  ],
};
interface Todo {
  userId: number;
  id: number;
  title: string;
  completed: boolean;
}
export const api = createApi({
  reducerPath: "api",
  tagTypes: ["Post", "Claim"],
  baseQuery: fetchBaseQuery({
    baseUrl: "https://claimsdemo.assist360.com.sg/api",
    prepareHeaders: async (headers, { getState }) => {
      const token = await AppUtil.getToken();
      if (token) {
        headers.set("Authorization", `Bearer ${token}`);
      }
      return headers;
    },
  }),
  endpoints: (builder) => ({
    resetPassword: builder.mutation<string, string>({
      query: (email) => ({
        url: "Account/reset-password-request",
        method: "POST",
        body: JSON.stringify("nagarasusubha@gmail.com"),
        headers: {
          "Content-Type": "application/json",
        },
      }),
    }),
    fetchImageData: builder.mutation<string | null, string>({
      query: (dataURL) => ({
        url: `Common/downloadfile/${dataURL}`,
        method: "GET",
        responseHandler: (response) => response.blob(),
      }),
      transformResponse: async (blob: Blob) => {
        return new Promise<string | null>((resolve, reject) => {
          const reader = new FileReader();
          reader.onloadend = () => {
            resolve(reader.result as string);
          };
          reader.onerror = () => {
            reject(null);
          };
          reader.readAsDataURL(blob);
        });
      },
    }),
    posts: builder.query<IPostResponse, IPaginationQuery>({
      providesTags: ["Post"],
      queryFn: async (args, api, extraOptions, baseQuery) => {
        console.log("args", args);
        const result = await baseQuery({
          url: "http://localhost:3000/posts",
          params: args,
        });
        return { data: result.data as IPostResponse };
      },
      merge: (oldData, newData) => {
        return {
          ...oldData,
          ...newData,
          data: [...oldData.data, ...newData.data],
        };
      },
      serializeQueryArgs: ({ endpointName }) => {
        return endpointName;
      },
    }),
    claims: builder.query<
      {
        data: IClaim[];
        pagination: Pagination;
      },
      IPaginationQuery
    >({
      providesTags: ["Claim"],
      query: (args) => ({
        url: "Claims",
        method: "GET",
        params: {
          pageNumber: args._page,
          pageSize: args._per_page,
        },
      }),
      transformResponse(baseQueryReturnValue: IClaim[], meta, arg) {
        let pagination = JSON.parse(
          meta?.response?.headers.get("pagination") as string
        ) as Pagination;
        return {
          data: baseQueryReturnValue,
          pagination: pagination,
        };
      },

      // transformErrorResponse(baseQueryReturnValue, meta, arg) {
      //   let pagination = JSON.parse(
      //     meta?.response?.headers.get("pagination") as string
      //   ) as Pagination;
      //   return {
      //     ...baseQueryReturnValue
      //   };
      // },
      merge: (oldData, newData) => {
        return {
          ...oldData,
          ...newData,
          data: [...oldData.data, ...newData.data],
        };
      },
      serializeQueryArgs: ({ endpointName }) => {
        return endpointName;
      },
    }),
  }),
});

export const {
  useResetPasswordMutation,
  useFetchImageDataMutation,
  usePostsQuery,
  useClaimsQuery,
} = api;

export const store = configureStore({
  reducer: {
    [api.reducerPath]: api.reducer,
  },
  middleware: (getDefaultMiddleware) =>
    getDefaultMiddleware().concat(api.middleware),
});
